### ISSUE TITLE
Is it planned to fix this Radar?

### ISSUE THREAD

**Issue by HIMix** [Mykybo/PUBG-Radar#3]
Looks like there's update to get this thing working again.
I checked main repo Issues and found that there's a guy who fixed Radar after the update March 12th.

Here's a comment on main repo: 
https://github.com/AiYinZiLeGong/PUBG-Radar/issues/149#issuecomment-372901087

Also at that fixed repo there's an Issue with info what he changed to get Radar working again:
https://github.com/Jerry1211/Radar/issues/2

The question is:
**Do you plan to fix your version?**

**Comment by Mykybo** [comment]
I will have a look when I get home.

**Comment by PiniginS** [comment]
@Mykybo In PacketParser.kt need add readBit() after val chIndex = readInt(MAX_CHANNELS)
Like this:
val bReliable = readBit()
val chIndex = readInt(MAX_CHANNELS)
readBit()

But i have error with stuck in left corner after this.

**Comment by Hypn0sys** [comment]
@Mykybo @PiniginS Same problem for me, stick in left corner.
Any hint ?

**Comment by nengbowan** [comment]
i will try it , today night . if it can work , i will remind man ,all of here .

**Comment by Mykybo** [comment]
PUBG packets are now encrypted.
